### ISSUE TITLE
Feature Request: delete own rating (or even selected student ratings)

### ISSUE THREAD

**Issue by sascha-serwe** [learnweb/moodle-mod_ratingallocate#102]
Some teachers tend to test their acitivities before publishing them. If they try to rate the choices by simulating student role (or by using test students) this test ratings will be used for allocation and therefore disturb the allocation algorithm.

Therefore it should be possible to delete ratings. In my opinion there are several options to solve this. Any idea itself can solve the problem. But they could also coexist and supplement each other.

Idea 1.
Option to delete his/her own rating for every user/rater.
This option could be implemented in the "edit rating"-Screen.
However: it might be useful to integrate a popup warning after selcting delete:
"Do you really want to delete your rating? The data will be lost and to be included in the allocation process you have to submit a new rating before the rating ends."
![delete_own_rating](https://cloud.githubusercontent.com/assets/19570540/15540830/bf55b448-2289-11e6-8d85-37fef761ebc0.jpg)

Idea 2.
A bit more general would be the option to delete ratings from other users. Only teachers should be allowed to do that. It could be integrated in the "ratings and allocations"-Table. 
The standard moodle choice activity has a comparable feature and it could be solved similarly (for moodle choice see the "view responses"-table): 
There should be an additional column (e.g. at the end, could be the first column as well) with a checkbox for each user. Furhermore a "select all" and a "deselect all" text and a button (or select box) to delete the selected ratings (maybe again with a popup warning).

![delete_user_ratings](https://cloud.githubusercontent.com/assets/19570540/15540838/c6f8a0d4-2289-11e6-98ff-19b41a654ed9.jpg)

**Comment by tobiasreischmann** [comment]
Deleting of own ratings was added.
