### ISSUE TITLE
Moodle - Task scheduled

### ISSUE THREAD

**Issue by angober** [learnweb/moodle-mod_ratingallocate#105]
Hi, when you deleted the plugin in Moodle, it doesn´t delete in database moodle (mdl_task_scheduled) the reference to task scheduled and when executed cron.php I see this notice:

PHP Notice:  Failed to load task: \mod_ratingallocate\task\cron_task* line 268 of /lib/classes/task/manager.php: call to debugging()
* line 475 of /lib/classes/task/manager.php: call to core\task\manager::scheduled_task_from_record()
* line 66 of /lib/cronlib.php: call to core\task\manager::get_next_scheduled_task()
* line 61 of /admin/cli/cron.php: call to cron_run()
 in /aplicaciones/moodle/e-formacio/e-formacio-eva/lib/weblib.php on line 2949

**Comment by tobiasreischmann** [comment]
Unfortunately, this is a bug in the moodle core.
I fixed it and created a tracker entry with the pull request.
Please have a look at [](https://tracker.moodle.org/browse/MDL-54892)
Till it is fixed you only can either apply the patch in your system or delete the task manually.

**Comment by angober** [comment]
Ok, thanks

**Comment by tobiasreischmann** [comment]
The issue is fixed for 3.0 and 3.1 and comes with the next release cycle.
See https://tracker.moodle.org/browse/MDL-54892
Issue closed.
