### ISSUE TITLE
Manuell allocation view

### ISSUE THREAD

**Issue by NinaHerrmann** [learnweb/moodle-mod_ratingallocate#109]
When editing the allocation manually the line "there are no users you could allocate" appears
![eingeklappt](https://cloud.githubusercontent.com/assets/18289780/16870308/3a9fd1e6-4a81-11e6-83f7-fce8c04398a4.png)
However when the button "Show all users" is clicked the expected menu appears.
![aufgeklappt](https://cloud.githubusercontent.com/assets/18289780/16870395/904b2348-4a81-11e6-8420-d41a5856bb92.png)

**Comment by Dagefoerde** [comment]
You can see that the first screenshot says "Only users who rated at least ..." and none are shown, whereas the second screenshot clearly indicates that four users have submitted choices.

**Comment by tobiasreischmann** [comment]
Probably, the students were already allocated. The intention of the first page is to show all those students, who rated but were not yet allocated. To enable the teacher to easily view all those students the algorithm could not allocate. However, the help text does not really state that. I will adjust the text accordingly.
