### ISSUE TITLE
Sorting of Ratings and Allocations Table

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#11]
It is requested, that the distribution table can be sorted manually. Apparently it is not comprehensible enough. An alternative to the current "sorting" would be for example alphabetically or by group.

The easiest and most convenient way is to just have it sorted by group - and to have this written in the code, so no more buttons for the user. The sorting could maybe be done in the same function where the allocated group per user is highlighted with the black box?

Note: A good sorting may also be interesting for a possible export of the table..

**Comment by tobiasreischmann** [comment]
The distribution table should be rebuild anyway. The links to the user profiles are not moodle like. 
Isn't there a possibility in moodle to create a sortable table? Then it could be easily sorted by name, by clicking on the column. The question is how sorting by group could be handled this way.
Same problem for manual allocation.

**Comment by SonjaKoenig** [comment]
Apparently something like this exists for moodle (sortable):
https://docs.moodle.org/dev/lib/tablelib.php

Sorting by group should be just as easy as sorting by name if we include the group name as a column.
The question is just if we can link the database easily to it? We should come back to this, when the time is right.

**Comment by tobiasreischmann** [comment]
Waiting for #77

**Comment by abias** [comment]
Hi Tobias, 

now that #77 is integrated, do you think you can tackle this issue anytime soon?

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Already in progress and almost finished. ;)
See feature/improved_ratingtable.

**Comment by abias** [comment]
Thanks, Tobias, for the update. I don't have time at the moment to look at the branch, but please ping us if you need testers.

**Comment by tobiasreischmann** [comment]
Sorting was added in #133
