### ISSUE TITLE
Publishing the allocation should not be possible if the allocation algorithm has not yet run

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_ratingallocate#125]
Hi there,

first, I want to wish you a happy and healthy new year! :)

Second, we had a complaint about an unhandled possibility that leads to a status that cannot be undone. The scenario is the following:
A teacher creates a new ratingallocate activity, let the students vote for their choices. After the voting period is over, he presses the button "Publish Allocation" by mistake - he wanted to start the allocation algorithm.

In this case following happens: the never done allocation is published (and that means exactly no allocation). The bad thing about this mistake ist that he cannot make this undone and cannot continue working with the data. In this case the work with the plugin was so to speak waste of time.

In the section "Publish Allocation" is the hint "There are no allocations yet. Please see the modify allocation section.". However this can obviously been overread.

So it would be great if there could be a "Are you sure you want to publish the allocation although the algorithm has not run yet" question when clicking the button without an existing allocation. 
Or, another possibility is to disable the button until at least the allocation algorithm has been run once.

Admins also cannot undo the publication within the GUI. Maybe that's also an aspect to think about so that we can help users if they did something wrong.

Cheers,
Kathrin

**Comment by tobiasreischmann** [comment]
Hey Kathrin,
the button to publish an allocation is usually disabled, until at least one allocation is created. Also, even after publishing the allocation, it is still possible to run the algorithm or edit the allocation manually. The only feature, which is then disabled is the possibility of automatically sending mails.
However, i like the idea to display an warning dialog when publishing the allocation.
Cheers,
Tobias

**Comment by Kathrin84** [comment]
Hi Tobi,
thanks for your reply. I did my test in our productive Moodle (3.0) and there the above mentioned scenario is possible.
Now I tested it with your latest version and Moodle 3.2 and there it works as you described it. Sorry for the inconveniences...
