### ISSUE TITLE
Disable changes to setting "Rating Strategy" if student(s) already voted 

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_ratingallocate#126]
Hi Tobias,

when talking about another issue, Alex and I came up with this issue.
With the current version v3.2-r1 (and of course also the older ones) it's possible to change the rating strategy anytime.
This may cause problems if students saved their votes and then the strategy is being changed. The saved values stay, but they aren't transformed to suitable values of the other strategy as it's simply not possible in my point of view. So students that already voted for their preferences with the old strategy may vote for something they did not like to have voted for with the newly selected strategy.

To prevent such problems, I suggest to disable changes to the rating strategy in the settings if the voting period has already started and there are already saved votings.

Cheers, Kathrin

**Comment by abias** [comment]
Just as a note: Disabling changes to the strategy settings as soon as the first student has voted would then align with the strategy of mod_quiz to allow changes to a quiz instance.

**Comment by tobiasreischmann** [comment]
I agree. However, I would like to couple this to enabling teachers to delete existing ratings. This is a necessary enhancement anyway.

**Comment by Laur0r** [comment]
Fixed with #252
