### ISSUE TITLE
Course Status Updates

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#13]
The status of the course with the allocation activity should be updated when certain events around the plugin hit. Especially when the allocation is fully complete and the users can view their results.
There are functions that look like 'pluginname_print_overview' which could help quite a lot here.
It may also be highly advisable to make the updates time out after a while. You don't want to see this for months.

Currently the activity description is displayed (if you tick the correct box on mod_form). This might be the correct spot to implement this.

**Comment by tobiasreischmann** [comment]
Nice to have. Please submit a pull request :)

**Comment by SonjaKoenig** [comment]
I can give it a try! :)

**Comment by Kathrin84** [comment]
The course status updates should cover the sights of the students and the teachers the following way:
* Students should see in that block that they have to do their ratings if the ratings phase has started. It should be deleted if the student has saved his choices.
* Teachers should be informed, if students could not be allocated to any group, so they have allocate those students manually to a choice. If all students are allocated, the hint should be deleted in this block.

**Comment by Kathrin84** [comment]
Hi Tobi, I've seen that my commits were automatically linked to this ticket... Unfortunately, there are multiple commits, although I always did a rebase. Now, I deleted the (unfortunatley wrong issue number (it should have been 132)) in the commit message, but the links here do not disapper. Maybe you can delete those? 
Sorry, and cheers, Kathrin

**Comment by tobiasreischmann** [comment]
Hey Kathrin,
I don't think this is possible. We just can ignore those references.
Cheers Tobias

**Comment by Dagefoerde** [comment]
Closing because `*_print_overview` is phased out until end of Moodle 3.6 and there is no corresponding method or functionality in Moodle 3.7+
