### ISSUE TITLE
Support Moodle dataformats for exporting the allocation table

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#130]
Hi,

Moodle 3.1 brought support for dataformats as a standardized way for exporting data. The documentation can be found on https://docs.moodle.org/dev/Data_formats and there is already one third party plugin on https://moodle.org/plugins/?q=type:dataformat.

On the other hand, mod_ratingallocate supports the export of the allocation table on /mod/ratingallocate/view.php?id=<ACTIVITY-ID>&action=show_alloc_table.

I would propose to think about replacing the existing export mechanism with support for dataformats anytime in the future.

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Hey Alex,
thanks for the idea. Actually, the table_sql API already offers to download the table in all known dataformats (csv, xlsx, ods, html, json). I just enabled the is_downloadable feature for the ratings tabel and adjusted the output in case of a download. The changes will come with the merge of #133.
Cheers,
Tobias

**Comment by tobiasreischmann** [comment]
#133 is merged. Will be in next release!
