### ISSUE TITLE
Suboptimal help string on allocation table page

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#131]
Hi,

in the language pack, there are two strings:

```
$string['allocation_statistics_description'] = 'This statistic gives an impression of the overall satisfaction of the allocation.
It is counting the allocations according to the rating the user has given to the respective choice.
In this case {$a->users} out of {$a->total} users got a choice they rated with "{$a->rating}".
For {$a->unassigned} users no choice has been allocated yet.';
$string['allocation_statistics_description_no_alloc'] = 'This statistic gives an impression of the overall satisfaction of the allocation.
It is counting the allocations according to the rating the user has given to the respective choice.
There are no allocations yet. For {$a->unassigned} users no choice has been allocated yet.';
```
which are shown on /mod/ratingallocate/view.php?id=<ACTIVITY-ID>&action=show_statistics.

I would propose two improvements:
* Please replace "table" in the first string with "statistic" to synchronize both strings.
* Please double-check if the statement "For {$a->unassigned} users no choice has been allocated yet.'" is really correct, especially for freshly created mod_ratingallocate instances. We have seen that on fresh instances, this string says "For 1 users no choice has been allocated yet.", but in fact nobody has voted yet! In german, it's even worse: Here we can read "Zum aktuellen Stand haben 1 Nutzer/innen ihre Bewertung abgegeben." which is definitely wrong.

Thanks,
Alex

**Comment by Kathrin84** [comment]
Hi, I've made a pull request for this issue:
https://github.com/learnweb/moodle-mod_ratingallocate/pull/145

**Comment by abias** [comment]
As the pull request has been merged, I will now close this issue
