### ISSUE TITLE
Index.php is in a horrible shape

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-mod_ratingallocate#135]
On the index.php there is still a call to add_to_log.
Additionally, the table is not very useful.

**Comment by abias** [comment]
Hi Tobias,

I agree with you that index.php could be polished. At least you should use the "incourse" page layout on this page like the Moodle core activities do.

> Additionally,  the table is not very useful.

In case you didn't know: The index.php file is a standard page in an activity module. Moodle core's block_activity_modules and some themes link to these pages to get an overview of the existing instances for each activity type. You can just show the list of existing instances there or show some more context-specific information like mod_forum or mod_assign do.

Thanks,
Alex
