### ISSUE TITLE
Show Available Spots

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#14]
During the rating process it might be interesting to see the maximum available spots for every choice in the listing. The maximum for available spots is an attribute that every choice already has, so it probably only has to be rendered.

This was requested quite often, however it is still advisable to make this optional if that is not a too big deal. To have it always displayed is also fine.

**Comment by tobiasreischmann** [comment]
Reasonable request.

**Comment by SonjaKoenig** [comment]
Since you think the effort for this one is low, could we increase the priority to 'high'? I think this would be a really useful feature to have.

We could resign to implement this with 'always displayed' and later make another issue to go a step back and make it optional (with a low priority and referenced).
