### ISSUE TITLE
Feature: Report with assignments only

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_ratingallocate#143]
For teachers it is rather hard to get an overview of the assigned items: There are the ratings table and the manual allocation table, which both show too much information if you only want to know the assignment. Extracting the information is a manual process that, depending on the number of items, is rather cumbersome.
Please add a report that shows the assignments only.

Until then, the following workarounds are possible:
- You can create groups from the allocations (and use Moodle's group features to "display" the assignments)
- If you are Excel-savvy, you can export to Excel and use formulas (VLOOKUP = SVERWEIS) to extract the desired information

**Comment by Kathrin84** [comment]
Hi Jan, 
we've read this issue and we are quite unsure if the already implemented feature for #154 is a duplicate of this or if you meant something else / something in addition?
Best, Kathrin
