### ISSUE TITLE
Description of allocated choice not shown on allocation overview page

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_ratingallocate#146]
Hi at all,
we encountered that a student cannot see the choice explanations anymore after he got allocated to a choice. We think that the student should at least see the description to the choice he has been allocated to.
Best, Kathrin

**Comment by Kathrin84** [comment]
I made a pull request for this:
https://github.com/learnweb/moodle-mod_ratingallocate/pull/147

**Comment by abias** [comment]
As the pull request has been merged, this issue can be closed.
