### ISSUE TITLE
Improvement: Highlight allocated choice for student

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_ratingallocate#152]
Hi,
if a user gets allocated to a choice, this user simply gets another table cell in the overview with the title  "Your allocation" and the name of the choice he got allocated to.

This might not be very eye catching, especially because the most important information is placed at the most bottom position.

How about highlighting this information within the table, or maybe even as a notification (with a bootstrap class for example) on top of the page.
If a user has a look at the plugin when after the allocation has been published, he quickly gets the most relevant information for that point in time.

Best, Kathrin

**Comment by tobiasreischmann** [comment]
Solved by #156

**Comment by tobiasreischmann** [comment]
The allocation is now visible on top in the notification and highlighted as a bootstrap label within the status table.
