### ISSUE TITLE
Improvement: Add information for users that could not be allocated

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_ratingallocate#153]
Hi,

there are always users that could not be automatically be allocated to a choice, either because they simply did not vote or because they voted in a way, that made it impossible for them to be allocated to a choice.
If the teacher does not check this and he publishes the results these users won't get an information about this. On the one hand, they don't get a message, because they were not allocated to a choice and on the other hand they simply don't see any status within the plugin. Whilst the other users who could get allocated get the additional table cell with their allocation, the overview simply does not change.

So, both aspects could be improved. The users without an allocation should also receive a message with the content, that the allocation has been finished, that they could not get allocated to a choice and that they should contact their teacher.
Furthermore, on the plugin's overview page, those users should also get the information (highlighted in red maybe) that they could not allocated.

So every user knows his current status and if something went wrong, he can quickly react and get in contact with the teacher.

Best, Kathrin

**Comment by tobiasreischmann** [comment]
Solved by #156

**Comment by tobiasreischmann** [comment]
Information is included in the status and the notification above it. Additionally, users are now getting a mail, if they rated and were not allocated at the time of publication.
