### ISSUE TITLE
Error in german translation

### ISSUE THREAD

**Issue by christianwolters** [learnweb/moodle-mod_ratingallocate#167]
Hi learnweb-team,

a colleague encountered an error (an not interpolated placeholder) in the german translation.
I compared the relevant strings in amos and found that **allocation_statistics_description** and **allocation_statistics_description_no_alloc** are not consistent in formatting[1] and placeholder usage.
The latter 
- uses a placeholder ("unassigned") that is not available before alloacation a.k.a. in no_alloc state
- leaves out the relevant placeholders "notrated" and "rated"

As I haven't worked with amos yet, I propose the following new version for **allocation_statistics_description_no_alloc** in the german lang-package

`Diese Statistik gibt einen Überblick über die Verteilung. Sie wird errechnet mit Bezug zu den Abstimmungen der Nutzer/innen für ihre Wahlmöglichkeiten. <br>
Es gibt derzeit noch keine Verteilungen. Bisher haben {$a->rated} Nutzer/innen eine Auswahl,  {$a->notrated} Nutzer/innen noch keine Auswahl getroffen.`

Best regards
Christian

[1] this issue is not related to the formatting, but the English text uses a list where the German text uses continues text. I personally find the list style more appropriate.

**Comment by christianwolters** [comment]
Hi learnweb-team,

I just submitted a contribution in AMOS, closing this ticket.

Cheers,
Christian

**Comment by Dagefoerde** [comment]
Danke! :)
