### ISSUE TITLE
Multi-Allocation of a student

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#17]
Some applications require it to be possible to allocate one student to multiple choices. 1 -> n
The idea is that the teacher makes on ratingallocate instance and the students sign up only for this one instance. Following, the teacher defines to how many choices a user can(!) be allocated (e.g. max 1 or max. 2) and the student defines into how many choices he wants(!) to be allocated to when he performs the rating. The algorithm then tries to allocate him into his n most favorite choices.

This definitely needs to be implemented as a rating strategy with the extra attribute of 'maximum possible allocations per user'. It challenges the algorithm on a whole new level.
Also the view.php for students has to be modified. The student has to somehow choose how many allocations he wants.

This has low priority.

**Comment by tobiasreischmann** [comment]
A similar not-moodle solution already exists in Münster. However, I am not sure if it is possible to adjust the existing algorithm to this needs or if a completely different algorithm is needed. 
In addition to the students view the manual allocation view has to be rethought as well.
Nice to have, but probably too time consuming.

**Comment by SonjaKoenig** [comment]
Agreed.

**Comment by abias** [comment]
Hi Tobias,

this issue was created by us two years ago and you tagged it with  Effort: Very High, Priority: Very Low.

During the last two years, I haven't heard this request from any of our teachers anymore. Thus, I would propose to close this issue as "Won't do" and focus on important things.

Thanks,
Alex

**Comment by JaMeZ-B** [comment]
> A similar not-moodle solution already exists in Münster. 

Hi @tobiasreischmann, could you point me to this solution (if it still exists)? 

I want to allocate tutors to visit each others in their sessions such that everyone visits two sessions and each session is visited by two tutors.

**Comment by tobiasreischmann** [comment]
Hey Jannes,
sorry that I did not respond. The solution I was talking about is used at the institute of information systems by Ingolf Terveer for the distribution of modules and seminars to bachelor and master students. He uses a sophisticated excel table for that, which solves a linear problem through the simplex method. I am unsure, how adaptable this is to your needs, if it is still of interest for you.
Cheers,
Tobias

**Comment by JaMeZ-B** [comment]
As it turned out, there weren't that many tutors to allocate so allocating them to a _single_ session and doing the second one by hand afterwards worked out nicely. My interest in a non-moodle/Learnweb solution involving proprietary software therefore is limited 😉

**Comment by Laur0r** [comment]
As stated before, this issue is too time-consuming for the low priority. Hence, we will close this as this won't be implemented.
