### ISSUE TITLE
Automated adjustment of visible strategy settings.

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#18]
The UI is very confusing concerning the rating strategies. Whenever a strategy is chosen, it would be wiser to hide the options for the not-chosen strategies - instead of disabling their forms.
It would also make the whole layout shorter and more clear.

Currently the code uses the 'disabledIf'-function from moodle, when the strategy options are loaded (mod_form.php line 141). Sadly I couldn't find anything like 'hiddenIf'.

**Comment by tobiasreischmann** [comment]
Something like hiddenIf does not exist. The issue is already known. It can only be fixed using javascript. But I haven't looked closer at it yet. 
Alternatively reload page on change of dropdown.

**Comment by SonjaKoenig** [comment]
I'm also nto very fond of forcing this via java script.

I think a reload on dropdown-change would not be too bad.
Since the dropdownlist is not very low on the page, the user might not even notice it much!

**Comment by Kathrin84** [comment]
First, the settings of the different rating strategies should be placed close to the equivalent dropdown where the rating strategy can be chosen over the dropdown menu (law of proximity):
![strategy_placing](https://cloud.githubusercontent.com/assets/4711883/11425196/7000c870-9453-11e5-807f-76b9f2155613.png)

Furthermore, not all of the rating strategy settings should be displayed as a long list. Only the settings of the currently chosen strategy should be visible to the user.
With every change of the dropdown the setting should adapt on the fly to the new selection.
