### ISSUE TITLE
Feature request: notify users who didn't vote 

### ISSUE THREAD

**Issue by fritzkrueger** [learnweb/moodle-mod_ratingallocate#198]
At the moment I am encountering a problem after publishing a distribution: users who didn't vote during the votingphase do not get notified, even if they are assigned manually by the course instructor. 

After looking into the problem and the locallib.php I guessed it could be something to do with the check for sending notifications to the users (around ln. 1138). There it checks (as far as I can tell) if a member of the course voted and then if a notifications should be send.

My question now is: would it be possible to add a function to inform all members who were assinged to a distribution, even if they didn't specifically vote? 
I was told that it was possible (and worked) while the plugin was still sending emails instead of system notifications.

**Comment by Laur0r** [comment]
Is merged with #270
