### ISSUE TITLE
Bulk upload choices and other billable requirements of fair allocation

### ISSUE THREAD

**Issue by yukito8000** [learnweb/moodle-mod_ratingallocate#206]
Dear Fair allocation developers,
Thank you very much for your great contributions to developing and supporting the fair allocation plugin. Our university has been used this plugin for over 4 years. Our teachers and students really like this function. With the increase of our student number and teacher number, we are having some specific needs which might need customized development. We are willing to pay for the development. 

Could you please suggest how can we contact and discuss the further details with you?

Background:
Teachers will provide over 600 projects for 600 students to choose, each student can only choose one project. To make it fair, we are using fair allocation's rank choice option. The majority functionality can support our needs, it will be great if the following requirements can be supported as well:

1. Bulk upload for a large number of choices
Details: our teachers need to create over 600 choices, it will be great if there can be a bulk upload function to allow teachers to use spreadsheet to import the choices.
2. Group restriction for each choice
Details: we want to limit some choices only available for certain groups of students to choose, it would be nice if each choice can allow teachers to set group restriction, the groups are connecting to the groups in Moodle
3. Prior students
Details: Before the random allocation, teachers want to manually allocate some students first, and then, the remaining students will be allocated according to their rank choice randomly. We prefer to have an option in the activity settings, if teachers need this function, they can enable it. Once this option is enabled, teachers will have the configurable sub-options to set. These sub-options are the reasons and evidence which are needed before the teachers to manually allocate the prior students. For example, the sub-options can be summer project experience, additional learning activities evidence. Teachers can tick the check box of these sub-options on the setting page. Having these settings, teachers can select prior students before the random allocation, and sub-options are required for teachers to select and teachers can upload attachments and provide a text description as evidence.

Thank you very much.
Best wishes,
Na Li (Lina)

**Comment by NinaHerrmann** [comment]
Hello Na Li,
Thanks for being interested in our plugin!
The changes you requested sound good but none of us has the time to develop them. 
You might either request a moodle partner or a freelancer. However, we can not guarantee that we have the time to maintain it. 
Sorry for the maybe not so helpful answer.
Best regards, 
Nina

**Comment by yukito8000** [comment]
> Hello Na Li,
> Thanks for being interested in our plugin!
> The changes you requested sound good but none of us has the time to develop them.
> You might either request a moodle partner or a freelancer. However, we can not guarantee that we have the time to maintain it.
> Sorry for the maybe not so helpful answer.
> Best regards,
> Nina

Hi Nina,
Thank you very much for your kind reply. That's very helpful. We will contact Moodle partner then.
Best wishes,
Lina
