### ISSUE TITLE
Feature request: filter by group / ratingallocate by group

### ISSUE THREAD

**Issue by Bambuspony** [learnweb/moodle-mod_ratingallocate#210]
we already have groups lets say 10 in the course and have therefore 10 times the ratingallocate on page [only available for the specific group] - as we want to divide them over i.e. 15 stations (each week another group). So it would be great to have an option that the "show_ratings_and_allocation_table" can be filtered by existing groups. So we can check, if all from the specific group did choose.
(in this case we don't use the option to make groups by the plugin, we only use the allocation)

On top it would even be great to only have 1 ratingallocate on page, but with group possibility - and so only for some specific groups available.

**Comment by NinaHerrmann** [comment]
Sounds like a nice feature, however we are currently lacking resources to add features to the plugin.

**Comment by Bambuspony** [comment]
Yes, understand. We will use the plugin as help for our "Blockpraktikum" to divide (or better let divide) already grouped students to different stations. Or do You know another plugin, that will divide group members by timeslot (1-2 weeks) to a ressource (Station)? Or how do/would You do this?

**Comment by Laur0r** [comment]
This scenario should now be possible with ratingallocate. You can restrict choices so that only specific groups can see and vote for them and filter the ratingallocate table accordingly to only be shown all users for this group.
