### ISSUE TITLE
Dock users names / column headers in the overview table

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [learnweb/moodle-mod_ratingallocate#212]
Hi all,

1. It would be helpful to dock the users names on the left hand side when scrolling to the right in the overview table of the allocating results.
/mod/ratingallocate/view.php?id=XXXXXX&action=show_ratings_and_allocation_table

2. It would also be helpful to display the column headers when scrolling downwards in order to reach the horizontal scrolling bar. Another solution would be to dock the horizontal scroll bar to the bottom of the view port.

If there are a lot of options and users to display, the users names (left column) and the titles of the available options (column headers) will scroll out of view, this makes the step "manual corrections of the automated allocation" difficult to handle.

It could work as in the grade report, see screenshot!
.../grade/report/grader/index.php?id=XXXX

<img width="510" alt="grade_report_dock_left" src="https://user-images.githubusercontent.com/72548805/113899573-39dff300-97cd-11eb-96c8-fb02ccbccc77.png">

Thank you 
Wiebke

**Comment by Laur0r** [comment]
This feature is merged with #255
