### ISSUE TITLE
Confirmation Dialog At Algorithm-Start

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#22]
When the algorithm is started by the button-click, the user should be asked to confirm his wish.
This should only be done when there has already been an allocation and should therefore warn the user about the consequences.

**Comment by tobiasreischmann** [comment]
Should be a more reasonable solution than #21.

**Comment by tobiasreischmann** [comment]
The branch https://github.com/learnweb/moodle-mod_ratingallocate/tree/feature/confirm-dialog shows a implementation of a confirmation dialog using existing YUI functions.
However it is not possible to query if there are any allocations yet. Is this feature necessary?
Possibilities would be either trying to solve it via ajax or redirect on an own page, when confirmation is needed.

**Comment by cl-a-us** [comment]
This seems to be a feasible solution. There is now need to have a confirmation dialog depending on whether there are already allocations or not.

**Comment by SonjaKoenig** [comment]
Yes, this was some leftover issue. Since we talked and clearified some things about how this whole plugin works, the need to poll for existing allocations is not needed anymore.
We could implement a standard confirmation dialog which basically says "There won't be any changes, if this algorithm has run already." or disable the button after the algorithm has run or we could just let it all be the way it is. 
I'm still more fond of running the algorithm automatically anyways :>

**Comment by tobiasreischmann** [comment]
Fixed by #53
