### ISSUE TITLE
Feature request: Config option to always trigger distribution algorithm as background task

### ISSUE THREAD

**Issue by PhMemmel** [learnweb/moodle-mod_ratingallocate#228]
Request:
- Config option to disable the ability to trigger the immediate calculation of the distribution by a teacher
- The button should only trigger the background task(!) and tell the teacher he has to wait for the calculation to finish.

This is needed for moodle instances with possibly high load.

**Comment by PhMemmel** [comment]
@tobiasreischmann If I'd implement this feature, will this be reviewed and - if it passes review - merged?

**Comment by NinaHerrmann** [comment]
@tobiasreischmann is no longer actively programming (as far as I know correct me if you want to spend time on it ;) )
If you make it an admin option to enable this feature, I do not see a point not to merge it (assuming coding style, additional test etc.) 
However, I am wondering, the calculation should not have a major impact on your Moodle site besides for the person the calculation is done for.
What experiences did you have that made you think this would be necessary?

**Comment by NinaHerrmann** [comment]
For the context, the biggest course using the plugin has roughly 1000 students and we did not notice major issues.

**Comment by PhMemmel** [comment]
@NinaHerrmann Thank you for the information and the feedback about bigger courses.

Let's say I just want to be 100% sure this doesn't influence anything else on the node this operation is being run on. In bigger moodle instances there are dedicated machines for handling background tasks and I want to enforce that these machines are doing such tasks. This probably is only relevant for really big moodle instances.

And yes: I was thinking about an admin configuration option leaving everything as it is right now if this option hasn't been enabled by the moodle site admin.

**Comment by NinaHerrmann** [comment]
as I said feel free to code ;)
