### ISSUE TITLE
Automatic Algorithm Run option

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#23]
It would be nice to have the option to have the allocation algorithm run automatically after the voting phase is over.

This has an extremely low priority.

**Comment by tobiasreischmann** [comment]
Should be possible using a cron job.

**Comment by tobiasreischmann** [comment]
I thought about the topic:
The major problem is failure handling. So what if the cron execution is not able to finish successfully? How to lock the modul from parallel executions? Etc...
I came up with some solutions and followup questions on the issue:
* Is it necessary to support a execution by cron job and a manual execution or is the cron enough and the manual execution can be dropped?
* If it is not enough: Is it feasible to offer the user to buttons (one to trigger the manual execution and one to schedule the execution for the cron job). This would be combined with a checkbox in the settings to allow for an immediate scheduling for the cron after the rating period ended.

Most of the problems could of cause be handle by a message "something went wrong, please contact your favourite admin ;)". However, the plugin should not cause to much effort for the local admins!!

PS: This is just a short excerpt from all the scenarios we came up with. But this comment field is probably not huge enough to describe them all. ;)

**Comment by SonjaKoenig** [comment]
Your second bullet point was the idea we had in mind. But basically, we only thought about the checkbox(!), not scheduling another date&time for the algorithm, since that might become too complex. When ticked, the button for manual execution could be simply disabled until the cron job has ended eitherway - successful or failed.

If the cron job fails, we could just tell "Try again by starting the algorithm manually. If this doesn't help, contact administrator."
Shouldn't a manual retry solve many failures? <- this is the core of the poodle :D

Greetings :)

**Comment by tobiasreischmann** [comment]
Fixed by #53
