### ISSUE TITLE
You were not allocated to any choice!

### ISSUE THREAD

**Issue by andreasschenkel** [learnweb/moodle-mod_ratingallocate#233]
Why does some users - not every user - get the information

Your allocation "You were not allocated to any choice!" 

after choosing? The Rating ends at time is not reached and the choises are still possible.
Side effect with "Estimated publication date"?

**Comment by irinahpe** [comment]
Can you give further information on how to recreate that error? Like a step by step intruction on which settings you are using in the ratingallocate-activity?

**Comment by andreasschenkel** [comment]
can not recreate the issue. will close it.
