### ISSUE TITLE
Support for Moodle 4.0

### ISSUE THREAD

**Issue by EureEminenz** [learnweb/moodle-mod_ratingallocate#234]
Since our provider had to deavtivate the plugin with the update to Moodle v. 4.0.2 I wanted to ask whether there are plans to merge #231  and ship a new version, so I could ask for reinstall at our provider.
Thanks and kind regards.

**Comment by Laur0r** [comment]
Thanks for the feedback. We have now merged and released a new version supporting Moodle 4.0.
Kind regards.
