### ISSUE TITLE
UI 'Rating is over'

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#24]
The UI Layout of the site after the rating period should be redesigned.
It is very important to have the buttons in the 'Distribution Table" section ordered properly. Maybe also the 'Start Distribution'-Button should be highlighted, so it is visable as 'the next step'.

Right now its just a bunch of salad if you see it for the first time :D

**Comment by tobiasreischmann** [comment]
That's true. 
Possible restructuring of the view within three categories:
Modify allocation
/ Publish allocation. Keine Buttons für unwichtige Sachen! Export In Einstellungen! Boxen zum aufklappen.

**Comment by tobiasreischmann** [comment]
That's true.
Possible restructuring of the view within three categories:
Modify allocation
* Automatic allocation by algorithm
* Manual allocation
Publish allocation
* Publish allocation
* Create groups
Reports
* Allocation table
* Allocation statistics

Each category becomes collapsable.
Export features are moved to the settings navigation.
Buttons only for important features. Links to tables are rendered as links and not as buttons.
Textual descriptions dependent on the current status. Disableling buttons if not allowed to be pressed.

**Comment by tobiasreischmann** [comment]
Done within 707d9e2ccc6400c1c7cf0159c185182df784e723

**Comment by SonjaKoenig** [comment]
It looks really nice. Thank you for your effort!
