### ISSUE TITLE
Descriptions appear twice when opening the activity

### ISSUE THREAD

**Issue by nisaDoc** [learnweb/moodle-mod_ratingallocate#244]
Hello,

we have a problem with activity descriptions. They appear twice when opening the mod_ratingallocate activity.
We installed this plugin on Moodle 4.1.2. Could you please fix it? Thanks :)
![image](https://user-images.githubusercontent.com/52955347/228012425-bdb0c954-b767-462e-95ce-9be5ee828803.png)

Cheers,
Nisa

**Comment by lucaboesch** [comment]
Didn't #237 fix this?

**Comment by nisaDoc** [comment]
at least I could replicate it in the v4.0-r1. Where did you fix? In which version?

**Comment by NinaHerrmann** [comment]
Thanks Luca!
