### ISSUE TITLE
UI languages

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#25]
There are some minor language issues, especially in the english version of the plugin.

Basically everything should be checked and adapted so the denotations fit to eachother.

**Comment by SonjaKoenig** [comment]
1. Ratingallocate as a new, own name or make it at least a little more correct by calling it 'Ratingallocation'?
2. Isn't the 'distribution' an 'allocation'? I wouldn't introduce new words, where they aren't needed.

**Comment by SonjaKoenig** [comment]
3. We should decide whether it is 'voting' or 'rating'? Because of the plugin title I'd go with 'rating.

**Comment by tobiasreischmann** [comment]
The name of ratingallocate was done before my time. Not it is hard to rename the plugin. That's one of the reasons we decided to leave it the way it is now. 
We agree on the proposed changes under 2.
We are happy if you provide us with solution for further unfitting terms .

**Comment by tobiasreischmann** [comment]
I would say this is already fixed.
