### ISSUE TITLE
Timeout Error Message

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#27]
Sometimes the algorithm times out because it's time exceeds the max. php-time-limit.
There are some possibilities to circumference the problem as a whole but it is safer to have the user at least notified what is going on.
I suggest that the algorithm runs firstly without notification. If it then crashes, the user will probably try to start it again. This should be the point where the user should be notified with something like this: "We detected that the algorithm could not finish. Please contact your administrator."

This is fairly easy as you just need a failed-boolean set to true, which is set to false when the algorithm finishes properly. Then just ask for the boolean and also check if this is not the first run.

**Comment by tobiasreischmann** [comment]
Time flag when the allocation started. If the flag is set, no additional allocation can be started. Before 5min time frame show message "Allocation still in progress, please refresh page after a short period of time". After 5 min show message "We detected that the algorithm could not finish. Please contact your administrator.". When the allocation finishes correctly unset the time flag.

**Comment by tobiasreischmann** [comment]
See #74
