### ISSUE TITLE
moodle_database::get_in_or_equal() does not accept empty arrays

### ISSUE THREAD

**Issue by Richardvi** [learnweb/moodle-mod_ratingallocate#280]
In our Moodle task log, we see these errors. Is seems the 'Fair allocation' module can't be deleted from a course.

Execute adhoc task: core_course\task\course_delete_modules
Adhoc task id: 598343
Adhoc task custom data: {"cms":[{"id":"487969","course":"18658","module":"44","instance":"7","section":"336728","idnumber":"","added":"1696334867","score":"0","indent":"0","visible":"1","visibleoncoursepage":"1","visibleold":"1","groupmode":"0","groupingid":"0","completion":"0","completiongradeitemnumber":null,"completionview":"0","completionexpected":"0","completionpassgrade":"0","showdescription":"0","availability":null,"deletioninprogress":"1","downloadcontent":"1","lang":""}],"userid":"782","realuserid":"782"}
... started 07:34:06. Current memory use 5.8 MB.
Debugging increased temporarily due to faildelay of 30720
... used 170 dbqueries
... used 1.5811660289764 seconds
Adhoc task failed: core_course\task\course_delete_modules,Coding error detected, it must be fixed by a programmer: The course module 487969 could not be deleted. Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays: /home/learn/public_html/lib/dml/moodle_database.php(778) #0 /home/learn/public_html**/mod/ratingallocate/lib.php(172)**: moodle_database->get_in_or_equal(Array)
#1 /home/learn/public_html/course/lib.php(900): **ratingallocate_delete_instance('7')**
#2 /home/learn/public_html/course/classes/task/course_delete_modules.php(66): course_delete_module('487969')
#3 /home/learn/public_html/lib/classes/cron.php(508): core_course\task\course_delete_modules->execute()
#4 /home/learn/public_html/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task(Object(core_course\task\course_delete_modules))
#5 /home/learn/public_html/lib/classes/cron.php(128): core\cron::run_adhoc_tasks(1696397646, 0, true, 1696397642)
#6 /home/learn/public_html/admin/cli/cron.php(186): core\cron::run_main_process('180')
#7 {main}
Backtrace:
* line 508 of /lib/classes/cron.php: call to core_course\task\course_delete_modules->execute()
* line 302 of /lib/classes/cron.php: call to core\cron::run_inner_adhoc_task()
* line 128 of /lib/classes/cron.php: call to core\cron::run_adhoc_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()

**Comment by Richardvi** [comment]
Using Moodle 4.2.2, PHP 8.0

**Comment by PhMemmel** [comment]
I believe this had been fixed by #279, but there has not been a release yet. Can you doublecheck?

**Comment by Richardvi** [comment]
I'm not so good with Github. If it's not released, we will have the latest released version and not the fix.

Can you direct me to what has been changed?

**Comment by Richardvi** [comment]
Ah sorry, found it. I think these are the changes: https://github.com/learnweb/moodle-mod_ratingallocate/pull/279/files

**Comment by Richardvi** [comment]
Nope. My version of lib.php looks different. Am I behind in versions? My lines look like this:

![image](https://github.com/learnweb/moodle-mod_ratingallocate/assets/5486910/760075c1-3dc1-4f86-8131-d3010a33d609)

**Comment by Laur0r** [comment]
I think you are still on the release v.4.2-r1. I have now published a new release (v4.3-r1) which incorporates the changes and should fix your problem.

**Comment by Richardvi** [comment]
Thanks for pushing the update. I've installed it now. I hope this will fix it :)
