### ISSUE TITLE
Minor typo in langstring

### ISSUE THREAD

**Issue by mwreichel** [learnweb/moodle-mod_ratingallocate#285]
Hi,
one of our teachers found an incorrect langstring, we would like to report to you:
$string['strategy_order_setting_countoptions'] = 'Minimum number of fields the user has to vote on (**smaller** than or equal to the number of choices!)';

To be correct, it should be written ... instead.
$string['strategy_order_setting_countoptions'] = 'Minimum number of fields the user has to vote on (**greater** than or equal to the number of choices!)';

We would appreciate, if you could fix this in one of the next versions of the plugin. I would change it afterwards in German. :-)

Thanks,
kind regards

Martin

**Comment by irinahpe** [comment]
Hi,
thank you for your remark, but the setting this language string describes, defines how many of the existing choices the users have to rank, so it should indeed be smaller or equal to the number of choices (the users can't rank more choices than exist).

**Comment by mwreichel** [comment]
Ok, thanks for your feedback.
