### ISSUE TITLE
>1 Ratingallocation

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#29]
Some courses might implement more than one rating allocation activity. There are a few problems which follow this and the user should sometimes even be informed about:

1. Warn the user that the allocations may alter the same groups. But inform that he can keep(!) existing users in them.
2. Because of 1 the user should explicitly be warned, that the publishing is a one-way-road! He can only drop everything or nothing. 
3. To reduce the risk of damage the user should get a "publishing-preview" which shows the groups, which are relevant for all allocation acitivites and the differences the publishing of the current activity would make.

**Comment by tobiasreischmann** [comment]
In the current implementation (without #16) the ratingallocate creates its own groups independent of those already existing (even if they have the same name!!!). Two or more instances of ratingallocate do therefore have their own destinct set of groups. Thus the problems described here do not exist, yet.
We have to think about these issues, when developing a group import feature. For now closed, but referenced in #16!
