### ISSUE TITLE
distribute_unallocated_task ad hoc task fails

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [learnweb/moodle-mod_ratingallocate#293]
We have installed the latest version of the plugin (v4.3-r1 (2023101900)) to our test server. In our testing we have discovered the distribute_unallocated_task.php ad hoc task fails to tun in our testing.

It looks like the execute function references 2 constants ACTION_DISTRIBUTE_UNALLOCATED_EQUALLY and ACTION_DISTRIBUTE_UNALLOCATED_FILL on line #51 which are not defined in that file. They are defined in locallib.php on lines #94 and 95, but this file is not required by the ad hoc task.

This is an output of the task log for the failling task - 
63503d3536ec:1075244 Execute adhoc task: mod_ratingallocate\task\distribute_unallocated_task
63503d3536ec:1075244 Adhoc task id: 14623038
63503d3536ec:1075244 Adhoc task custom data: {"courseid":"60011","cmid":"1280428","distributionalgorithm":"distribute_unallocated_fill"}
63503d3536ec:1075244 ... started 01:14:13. Current memory use 3.5 MB.
63503d3536ec:1075244 Debugging increased temporarily due to faildelay of 61440
63503d3536ec:1075244 ... used 1 dbqueries
63503d3536ec:1075244 ... used 0.012392997741699 seconds
63503d3536ec:1075244 Adhoc task failed: mod_ratingallocate\task\distribute_unallocated_task,Undefined constant "mod_ratingallocate\task\ACTION_DISTRIBUTE_UNALLOCATED_EQUALLY"
63503d3536ec:1075244 Backtrace:
63503d3536ec:1075244 * line 367 of /lib/cronlib.php: call to mod_ratingallocate\task\distribute_unallocated_task->execute()
63503d3536ec:1075244 * line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
63503d3536ec:1075244 * line 131 of /admin/cli/adhoc_task.php: call to cron_run_adhoc_tasks()
63503d3536ec:1075244 

We are running the latest plugin on Moodle 4.1.9 [4.1.9 (Build: 20240212)]

**Comment by PhMemmel** [comment]
Interestingly enough, the tasks are not failing on my instance, but when looking at the code they probably should, so I provided a fix. :)
