### ISSUE TITLE
Choice Descriptions (Publication Notifications & Moodle Groups)

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#41]
Apparently many users don't include enough information in a choice's title. So when the results are published, a student might just be notified that he got into "Tutorium 29", but has no idea when and where this will be.

So the request was, to include the corresponding choice's description in those notifications.

Also it was requested to pass the description for every choice along, when the Moodle Groups are created.

**Comment by tobiasreischmann** [comment]
Reasonable request.

**Comment by andrewhancox** [comment]
Tobias/Sonja,
I have submitted a pull request adding this functionality.
