### ISSUE TITLE
Call to set_time_limit(120) correct?

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#45]
See https://github.com/learnweb/moodle-mod_ratingallocate/blob/master/locallib.php#L177 - is it correct that you restrict script run time here to 120 secs or should this call rather be set_time_limit(0)?

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Also see #44

**Comment by tobiasreischmann** [comment]
Fixed by #53
