### ISSUE TITLE
Remove ratingallocate_user_outline() and ratingallocate_user_complete() functions?

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#46]
See http://git.moodle.org/gw?p=moodle.git;a=blob;f=mod/upgrade.txt;hb=master, section 2.7:

> The functions xxx_user_outline() and xxx_user_complete() have been removed from the majority of core modules (see MDL-41286), except for those that require unique functionality. These functions are used by the outline report, but now if they no longer exist, the default behaviour is chosen, which supports the legacy and standard log storages introduced in 2.7 (see MDL-41266). It is highly recommended you remove these functions from your module if they are simply performing the default behaviour.

Perhaps you might consider removing those functions as one of them is empty and the other one does not provide useful data.

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Agree
