### ISSUE TITLE
ddlfieldnotexist error when upgrading

### ISSUE THREAD

**Issue by ewallah** [learnweb/moodle-mod_ratingallocate#56]
Default exception handler: Field "RATINGALLOCATEID" does not exist in table "ratingallocate_allocations" 
line 119 of /mod/ratingallocate/db/upgrade.php

The mysql table field should be 'ratingallocateid'

release2015041301 version2.8-r2

**Comment by tobiasreischmann** [comment]
Sorry I haven't tested on mysql databases.
Have you tried your suggested fix to write the referenced column name in lower case?
Then I will fix it and create a new release.
