### ISSUE TITLE
Save Rating does not work in yes_no_maybe strategy

### ISSUE THREAD

**Issue by stefan612** [learnweb/moodle-mod_ratingallocate#63]
Saving does not take any effekt.

the reason may be somewhere here:
i get false in mod/ratingallocate/locallib.php:248
else if ($mform->is_submitted() && $mform->is_validated() && $data = $mform->get_data() ) 
so the save save_ratings_to_db() will not be reached.

If i try the just the yes/no - strategy... everythings works fine.

Someone any ideas about this issue?

Thanks
Stefan

**Comment by tobiasreischmann** [comment]
Can you describe your scenario in more detail?
(How many choices/ which strategy/ which settings/ which rating)
I tried to reproduce the issue, but everything works fine here.

**Comment by stefan612** [comment]
Well, i created a standard yes/neutral/no Strategy. Like shown in the attached image.
All settings are only default.
So after clicking "'Save changes" the form seems to be sent...
But unfortunately the mform - object seems not to have the submit - information.


![namenlos](https://cloud.githubusercontent.com/assets/4608243/8697308/424e71c0-2af4-11e5-996e-0c922418d027.jpg)

**Comment by tobiasreischmann** [comment]
Which moodle and php version are you using?
And are you running the platform in debugging mode? (Would be interessting to know if an error would have been displayed.
Additionally, can you have a look in your logdata if an entry like this is present:
![ratingallocate_log](https://cloud.githubusercontent.com/assets/9437254/8698486/069ac2b8-2aff-11e5-9927-afa996996263.png)
Note that the context of the logdata is the course and not the activity. (I will file this as a new issue)

**Comment by stefan612** [comment]
Well, it's a moodle 2.8.5.
PHP Version 5.5.14

Yes.. moodle is running in Debug - Mode.
Unfortunately i do not get any errors. Either in the webpage nor in the error log.
The logdata is empty too.
That's reasonable because following part of code will not be reached:
else if ($mform->is_submitted() && $mform->is_validated() && $data = $mform->get_data() ) {
                    // Save submitted data and call default page.
                    $this->save_ratings_to_db($USER->id, $data->data);
                    $renderer->add_notification(get_string('ratings_saved', ratingallocate_MOD_NAME), self::NOTIFY_SUCCESS);
                    return $this->process_default();
                }

Very strange...
Thanks a lot for your help :)

**Comment by tobiasreischmann** [comment]
Hmm, I have tested the plugin under the moodle versions 2.8.6 and 2.9.1.
The first one under php 5.5.9 and 5.4.42.
And in all cases is_submitted() is true.
I suppose you have the latest version of ratingallocate?

Are there at least logs for user accessed the plugin?
Can you maybe have a look, what formdata is submitted by the browser?
If I analyse the network with firebug I have an entry there for "submitbutton".
Alternatively you should get this entry if you run $mform->get_submitted_data() at the mentioned error line 248
Here an excerpt of my form data:
![ratingallocate_log](https://cloud.githubusercontent.com/assets/9437254/8700329/6c83fd0e-2b0b-11e5-9488-615a45354617.png)

**Comment by stefan612** [comment]
Well, in firebug it seems ok.
![namenlos](https://cloud.githubusercontent.com/assets/4608243/8701084/0b3526d6-2b10-11e5-8112-547ecb8ce8a0.jpg)

But using print_object($mform->definition_after_data()); is empty :/

**Comment by tobiasreischmann** [comment]
$mform->definition_after_data() is always empty since this method is not used in our plugin.
Use $mform->get_submitted_data() and $mform->is_submitted().
And if the second one is false maybe try to debug in. The method structure isn't that complex.

**Comment by stefan612** [comment]
Ahh... that was a typing error.
I meant $mform->get_submitted_data(). This is empty too.
So $mform->is_submitted() stays also false.
Strange behaviour. Well, let's see.

**Comment by tobiasreischmann** [comment]
Looks for me as if the submit button is not working properly.
Unfortunately this is Moodle standard component.
One more question for clarification:
When you press save, the page "reloads" ending in the same form again or does it redirect to the main view of the plugin?
What happens if you click cancle?

Another try:
Can you place a breakpoint at strategy_template_options.php:135 and tell me if errors is an empty array?

**Comment by stefan612** [comment]
>When you press save, the page "reloads" ending in the same form again or does it redirect to the >main view of the plugin?
That's exactly what happens. Strange is that in other strategy the button work properly. And i do not see any difference in the source code.
>What happens if you click cancle? 
Is the same like clicking "Save". 

Yes... the errors - array is empty too.
So.. it can only be a problem with the button - where i can not find any code difference

**Comment by stefan612** [comment]
Argh.. still not able to fix the problem.
I just debugged a bit deeper and found following:
There is a difference between in transmitted form elements:
In the strategy where everything work fine (yes/no  - strategy) there is following:
<input type="hidden" value="1" name="_qf__ratingallocate_strategy_yesno_mod_ratingallocate_view_form">

This element is missing in the  yes/neutral/no html output.

So when looking at the sourcecode i found out why the submitted data ($submission) gets an empty array:
\moodleform::_process_submission
        if (array_key_exists('_qf__'.$this->_formname, $submission) and $submission['_qf__'.$this->_formname] == 1) {
            if (!confirm_sesskey()) {
                print_error('invalidsesskey');
            }
            $files = $_FILES;
        } else {
            $submission = array();
            $files = array();
        }

So, the question is what is going wrong in the yes/neutral/no template because the _qf__ element is not set?!

**Comment by tobiasreischmann** [comment]
In this case please look in the html code of the yes_no strategy and the yes_no_maybe strategy.
Within the form element, there should be an div with style="display; none;".
Within this element all hidden fields are listed.
One of them should have a name like "_qf__ratingallocate_strategy_yesmaybeno_mod_ratingallocate_view_form"
Is this true for both of them?

**Comment by stefan612** [comment]
Yes that's the problem ;)
The _qf__ratingallocate_strategy_yesmaybeno_mod_ratingallocate_view_form
is missing there.

**Comment by tobiasreischmann** [comment]
Per Mail you reported, that the yes_maybe_no strategy isn't the only strategy, which is not working for you, but the strategies tickyes and lickert as well.
I recognized, that these three strategies have longer names than the others.
Could it be possible, that you have somehow a lengthrestiction of the html's name attribute within your browser?

**Comment by tobiasreischmann** [comment]
Otherwise set a breackpoint at lib/formslib.php:196 and look what is going wrong there.

**Comment by stefan612** [comment]
Ahh.. yes! I think that's it.
Our server is limit with:
suhosin.post.max_array_index_length	64	64
suhosin.post.max_name_length	64	64

So i think a change here will fix the problem!

Thanks a lot

**Comment by tobiasreischmann** [comment]
Finally :)
No problem!
