### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#64]
Hi,

I just upgraded the installed version of mod_ratingallocate from v2.8-r1 to v2.9-r2. 

The plugin now shows me on a old activity instance (which was already there before the upgrade) with the URL /mod/ratingallocate/view.php?id=41371&action=show_alloc_table this error message:

get_all_allocations() has been deprecated, please rewrite your code to use get_allocations
line 712 of /mod/ratingallocate/locallib.php: call to debugging()
line 301 of /mod/ratingallocate/locallib.php: call to ratingallocate->get_all_allocations()
line 530 of /mod/ratingallocate/locallib.php: call to ratingallocate->process_action_show_alloc_table()
line 61 of /mod/ratingallocate/view.php: call to ratingallocate->handle_view()

Is this something I should worry about? Could you please solve this deprecation warning in code?

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Hey Alex,
this is nothing you should worry about. It is just a legacy method, which should be rewritten someday and was therefor marked as deprecated by one of us. Nevertheless the method should work properly.
We will fix it however ;)
Greetings,
Tobias
