### ISSUE TITLE
 Pagination of Ratings and Allocations Table

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-mod_ratingallocate#72]
For huge courses the table of ratings and allocations is very huge.
Here a separation in different pages is needed.
Possibly extended by a searchbar.

**Comment by tobiasreischmann** [comment]
Waiting for #77

**Comment by tobiasreischmann** [comment]
Needs discussion if it is really wanted.

**Comment by abias** [comment]
Hi Tobias,

now that #77 is integrated, this issue could be discussed. 

I don't see a real benefit with paginating this page except reducing the page load time. From my point of view, this issues could closed as won't fix. What do you think?

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Hey Alex,
since the current state of the module had huge problems with large course (>800 students) this issue is mandatory from my point of view. It is also almost finished and will be integrated soon (feature/improved_ratingtable). ;)
Cheers,
Tobias

**Comment by abias** [comment]
Ah, well, ok. Thanks for the update then :)

**Comment by tobiasreischmann** [comment]
Initialbars and Pagination was added in #133
