### ISSUE TITLE
Think about the name of the plugin

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_ratingallocate#89]
Hi,

for historical reasons, the plugin's name is "ratingallocate" or "Ratingallocate". This string is used throughout the plugin's english language pack, it is even used as title on https://moodle.org/plugins/mod_ratingallocate. 

I am no native english speaker, but I dare to doubt that this title is ideal in the english language and explains well what the plugin does. I would like to ask you to think about simple but effective improvements to this title, for example "Rating & Allocate" and change all necessary strings in the language pack.

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Hey Alex,
you are absolutly right. It needs another name. But I'm not very satisfied with Rating & Allocate.
What do you think of the following examples:
- Rated Allocation
- Allocation by Preferences
- Allocation by Ratings
- Fair Allocation
- Rating & Allocation (The problem is that you can't really use this as a subject, similar to your example)
Cheers,
Tobias

**Comment by Kathrin84** [comment]
As I saw this ticket right now, just my two cents:
As the plugin in German is called '"Gerechte Verteilung" I spontaneously would vote for the proposal "Fair Allocation" or my second favorite one "Allocation by Preferences".

Cheers,
Kathrin

**Comment by abias** [comment]
Hi Tobias and sorry for my late feedback.

My opinions:
* We could argue if the allocation is really "fair" (= "gerecht" in german) or not. 
* If you think it's fair, then use "Fair Allocation" in english and keep "Gerechte Verteilung" as german name.
* If you don't think it's fair and the plugin just does an allocation based on facts (that's what I think), you could use "Rating and Allocation" in english (this does not diverge too much from the original pluginname and I don't find anything wrong in that labeling) and change the german name for the next major version to "Bewerten und Verteilen" or something like that.

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Hey Alex,
I decided to stick with "Gerechte Verteilung" and change the english name accordingly to "Fair Allocation".

**Comment by abias** [comment]
Ok, thanks for the update :)
