### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by SonjaKoenig** [learnweb/moodle-mod_ratingallocate#9]
Users requested a classic progress bar to see while the distribution algorithm runs. Nothing too fancy. Apparently there are already some modules and moodle-own-features which use progress bars (e.g. Language-Changer). This may could be an inspiration on how to get this done in moodle.

This has very low priority.

**Comment by tobiasreischmann** [comment]
Makes adoption of the algorithm necessary to inform site about changes. Probably high effort needed.

**Comment by Kathrin84** [comment]
As the algorithm works in the background, this issue is not up to date anymore and can be closed.

**Comment by tobiasreischmann** [comment]
When the algorithm is started manually, it is currently not running in the background.
However, a solution through adhoc tasks should be better than a progress bar.
See: https://docs.moodle.org/dev/Task_API#Adhoc_tasks

**Comment by tobiasreischmann** [comment]
See #74
