### ISSUE TITLE
Add email addresses to CSV export 

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_ratingallocate#90]
Hi Tobi,

we've got a request, if it would be possible to also export a user's email address in the CSV file.
This would increase the user's workflow because he wouldn't have to look up a users email address separately when dealing with the CSV.

In this context it's important to only export the email addresses if a user has the capability to view them. Before exporting this should be checked. Alex said that there's a function for.

If we would create a patch for this issue, would you accept it or do you have concerns about data privacy on this issue in general?

Cheers,
Kathrin

**Comment by tobiasreischmann** [comment]
Hi Kathrin,
if you use the respective capability, I have no concers regarding data privacy.
You can submit a pull request if you want. 
Just out of curiosity: For which purpose does a teacher need the e-mail adresses? The allocations should be send to the students automatically when published.

Cheers,
Tobias

**Comment by berb** [comment]
As the teacher might also export alloactions to use them outside of Moodle for various teaching purposes, a unique, globally valid identifier such as mail is very handy.

Greetings
Benjamin

**Comment by tobiasreischmann** [comment]
Ok, I agree that students' e-mail-adresses might be useful for the teacher for purposes outside of moodle.
However, I would be careful with the assumtion that mail is a unique, globally valid identifier. At least, not in every moodle installation. 
Cheers,
Tobias

**Comment by Kathrin84** [comment]
@tobiasreischmann, could you please have a look at my pull request?
That would be great! 

Thanks and see you soon in Konstanz. :)

**Comment by tobiasreischmann** [comment]
Sorry, it took me so long.
Your pull request looks good. 
However, user/lib.php:457 has many different scenarios, in which the email is shown to a user.
```
    if (in_array('email', $userfields) && ($isadmin // The admin is allowed the users email.
      or $currentuser // Of course the current user is as well.
      or $canviewuseremail  // This is a capability in course context, it will be false in usercontext.
      or in_array('email', $showuseridentityfields)
      or $user->maildisplay == 1
      or ($user->maildisplay == 2 and enrol_sharing_course($user, $USER)))) {
        $userdetails['email'] = $user->email;
    }
```
It could be interesting to include those:
- email is within the set of useridentityfields.
- the current user is the admin user.
- show a subset of emails for those users who defined that their email is shown to the current user in the current context.

I will accept the pull request. The possible extensions can be merged later.

**Comment by tobiasreischmann** [comment]
New issue for extension: #116
